###################################################################

# Created by write_sdc on Wed Dec 19 17:33:32 2018

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_max_area 0
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[99]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[98]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[97]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[96]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[95]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[94]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[93]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[92]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[91]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[90]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[89]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[88]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[87]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[86]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[85]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[84]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[83]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[82]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[81]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[80]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[79]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[78]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[77]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[76]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[75]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[74]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[73]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[72]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[71]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[70]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[69]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[68]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[67]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[66]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[65]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[64]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[63]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[62]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[61]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[60]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[59]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[58]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[57]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[56]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[55]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[54]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[53]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[52]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[51]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[50]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[49]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[48]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[47]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[46]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[45]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[44]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[43]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[42]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[41]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[40]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[39]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[38]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[37]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[36]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[35]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[34]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[33]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[32]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[31]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[30]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[29]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[28]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[27]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[26]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[25]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[24]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[23]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[22]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[21]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[20]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[19]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[18]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[17]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[16]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {sumIn[0]}]
set_load -pin_load 0.005 [get_ports {result[3]}]
set_load -pin_load 0.005 [get_ports {result[2]}]
set_load -pin_load 0.005 [get_ports {result[1]}]
set_load -pin_load 0.005 [get_ports {result[0]}]
set_max_capacitance 0.005 [get_ports {sumIn[99]}]
set_max_capacitance 0.005 [get_ports {sumIn[98]}]
set_max_capacitance 0.005 [get_ports {sumIn[97]}]
set_max_capacitance 0.005 [get_ports {sumIn[96]}]
set_max_capacitance 0.005 [get_ports {sumIn[95]}]
set_max_capacitance 0.005 [get_ports {sumIn[94]}]
set_max_capacitance 0.005 [get_ports {sumIn[93]}]
set_max_capacitance 0.005 [get_ports {sumIn[92]}]
set_max_capacitance 0.005 [get_ports {sumIn[91]}]
set_max_capacitance 0.005 [get_ports {sumIn[90]}]
set_max_capacitance 0.005 [get_ports {sumIn[89]}]
set_max_capacitance 0.005 [get_ports {sumIn[88]}]
set_max_capacitance 0.005 [get_ports {sumIn[87]}]
set_max_capacitance 0.005 [get_ports {sumIn[86]}]
set_max_capacitance 0.005 [get_ports {sumIn[85]}]
set_max_capacitance 0.005 [get_ports {sumIn[84]}]
set_max_capacitance 0.005 [get_ports {sumIn[83]}]
set_max_capacitance 0.005 [get_ports {sumIn[82]}]
set_max_capacitance 0.005 [get_ports {sumIn[81]}]
set_max_capacitance 0.005 [get_ports {sumIn[80]}]
set_max_capacitance 0.005 [get_ports {sumIn[79]}]
set_max_capacitance 0.005 [get_ports {sumIn[78]}]
set_max_capacitance 0.005 [get_ports {sumIn[77]}]
set_max_capacitance 0.005 [get_ports {sumIn[76]}]
set_max_capacitance 0.005 [get_ports {sumIn[75]}]
set_max_capacitance 0.005 [get_ports {sumIn[74]}]
set_max_capacitance 0.005 [get_ports {sumIn[73]}]
set_max_capacitance 0.005 [get_ports {sumIn[72]}]
set_max_capacitance 0.005 [get_ports {sumIn[71]}]
set_max_capacitance 0.005 [get_ports {sumIn[70]}]
set_max_capacitance 0.005 [get_ports {sumIn[69]}]
set_max_capacitance 0.005 [get_ports {sumIn[68]}]
set_max_capacitance 0.005 [get_ports {sumIn[67]}]
set_max_capacitance 0.005 [get_ports {sumIn[66]}]
set_max_capacitance 0.005 [get_ports {sumIn[65]}]
set_max_capacitance 0.005 [get_ports {sumIn[64]}]
set_max_capacitance 0.005 [get_ports {sumIn[63]}]
set_max_capacitance 0.005 [get_ports {sumIn[62]}]
set_max_capacitance 0.005 [get_ports {sumIn[61]}]
set_max_capacitance 0.005 [get_ports {sumIn[60]}]
set_max_capacitance 0.005 [get_ports {sumIn[59]}]
set_max_capacitance 0.005 [get_ports {sumIn[58]}]
set_max_capacitance 0.005 [get_ports {sumIn[57]}]
set_max_capacitance 0.005 [get_ports {sumIn[56]}]
set_max_capacitance 0.005 [get_ports {sumIn[55]}]
set_max_capacitance 0.005 [get_ports {sumIn[54]}]
set_max_capacitance 0.005 [get_ports {sumIn[53]}]
set_max_capacitance 0.005 [get_ports {sumIn[52]}]
set_max_capacitance 0.005 [get_ports {sumIn[51]}]
set_max_capacitance 0.005 [get_ports {sumIn[50]}]
set_max_capacitance 0.005 [get_ports {sumIn[49]}]
set_max_capacitance 0.005 [get_ports {sumIn[48]}]
set_max_capacitance 0.005 [get_ports {sumIn[47]}]
set_max_capacitance 0.005 [get_ports {sumIn[46]}]
set_max_capacitance 0.005 [get_ports {sumIn[45]}]
set_max_capacitance 0.005 [get_ports {sumIn[44]}]
set_max_capacitance 0.005 [get_ports {sumIn[43]}]
set_max_capacitance 0.005 [get_ports {sumIn[42]}]
set_max_capacitance 0.005 [get_ports {sumIn[41]}]
set_max_capacitance 0.005 [get_ports {sumIn[40]}]
set_max_capacitance 0.005 [get_ports {sumIn[39]}]
set_max_capacitance 0.005 [get_ports {sumIn[38]}]
set_max_capacitance 0.005 [get_ports {sumIn[37]}]
set_max_capacitance 0.005 [get_ports {sumIn[36]}]
set_max_capacitance 0.005 [get_ports {sumIn[35]}]
set_max_capacitance 0.005 [get_ports {sumIn[34]}]
set_max_capacitance 0.005 [get_ports {sumIn[33]}]
set_max_capacitance 0.005 [get_ports {sumIn[32]}]
set_max_capacitance 0.005 [get_ports {sumIn[31]}]
set_max_capacitance 0.005 [get_ports {sumIn[30]}]
set_max_capacitance 0.005 [get_ports {sumIn[29]}]
set_max_capacitance 0.005 [get_ports {sumIn[28]}]
set_max_capacitance 0.005 [get_ports {sumIn[27]}]
set_max_capacitance 0.005 [get_ports {sumIn[26]}]
set_max_capacitance 0.005 [get_ports {sumIn[25]}]
set_max_capacitance 0.005 [get_ports {sumIn[24]}]
set_max_capacitance 0.005 [get_ports {sumIn[23]}]
set_max_capacitance 0.005 [get_ports {sumIn[22]}]
set_max_capacitance 0.005 [get_ports {sumIn[21]}]
set_max_capacitance 0.005 [get_ports {sumIn[20]}]
set_max_capacitance 0.005 [get_ports {sumIn[19]}]
set_max_capacitance 0.005 [get_ports {sumIn[18]}]
set_max_capacitance 0.005 [get_ports {sumIn[17]}]
set_max_capacitance 0.005 [get_ports {sumIn[16]}]
set_max_capacitance 0.005 [get_ports {sumIn[15]}]
set_max_capacitance 0.005 [get_ports {sumIn[14]}]
set_max_capacitance 0.005 [get_ports {sumIn[13]}]
set_max_capacitance 0.005 [get_ports {sumIn[12]}]
set_max_capacitance 0.005 [get_ports {sumIn[11]}]
set_max_capacitance 0.005 [get_ports {sumIn[10]}]
set_max_capacitance 0.005 [get_ports {sumIn[9]}]
set_max_capacitance 0.005 [get_ports {sumIn[8]}]
set_max_capacitance 0.005 [get_ports {sumIn[7]}]
set_max_capacitance 0.005 [get_ports {sumIn[6]}]
set_max_capacitance 0.005 [get_ports {sumIn[5]}]
set_max_capacitance 0.005 [get_ports {sumIn[4]}]
set_max_capacitance 0.005 [get_ports {sumIn[3]}]
set_max_capacitance 0.005 [get_ports {sumIn[2]}]
set_max_capacitance 0.005 [get_ports {sumIn[1]}]
set_max_capacitance 0.005 [get_ports {sumIn[0]}]
set_max_fanout 4 [get_ports {sumIn[99]}]
set_max_fanout 4 [get_ports {sumIn[98]}]
set_max_fanout 4 [get_ports {sumIn[97]}]
set_max_fanout 4 [get_ports {sumIn[96]}]
set_max_fanout 4 [get_ports {sumIn[95]}]
set_max_fanout 4 [get_ports {sumIn[94]}]
set_max_fanout 4 [get_ports {sumIn[93]}]
set_max_fanout 4 [get_ports {sumIn[92]}]
set_max_fanout 4 [get_ports {sumIn[91]}]
set_max_fanout 4 [get_ports {sumIn[90]}]
set_max_fanout 4 [get_ports {sumIn[89]}]
set_max_fanout 4 [get_ports {sumIn[88]}]
set_max_fanout 4 [get_ports {sumIn[87]}]
set_max_fanout 4 [get_ports {sumIn[86]}]
set_max_fanout 4 [get_ports {sumIn[85]}]
set_max_fanout 4 [get_ports {sumIn[84]}]
set_max_fanout 4 [get_ports {sumIn[83]}]
set_max_fanout 4 [get_ports {sumIn[82]}]
set_max_fanout 4 [get_ports {sumIn[81]}]
set_max_fanout 4 [get_ports {sumIn[80]}]
set_max_fanout 4 [get_ports {sumIn[79]}]
set_max_fanout 4 [get_ports {sumIn[78]}]
set_max_fanout 4 [get_ports {sumIn[77]}]
set_max_fanout 4 [get_ports {sumIn[76]}]
set_max_fanout 4 [get_ports {sumIn[75]}]
set_max_fanout 4 [get_ports {sumIn[74]}]
set_max_fanout 4 [get_ports {sumIn[73]}]
set_max_fanout 4 [get_ports {sumIn[72]}]
set_max_fanout 4 [get_ports {sumIn[71]}]
set_max_fanout 4 [get_ports {sumIn[70]}]
set_max_fanout 4 [get_ports {sumIn[69]}]
set_max_fanout 4 [get_ports {sumIn[68]}]
set_max_fanout 4 [get_ports {sumIn[67]}]
set_max_fanout 4 [get_ports {sumIn[66]}]
set_max_fanout 4 [get_ports {sumIn[65]}]
set_max_fanout 4 [get_ports {sumIn[64]}]
set_max_fanout 4 [get_ports {sumIn[63]}]
set_max_fanout 4 [get_ports {sumIn[62]}]
set_max_fanout 4 [get_ports {sumIn[61]}]
set_max_fanout 4 [get_ports {sumIn[60]}]
set_max_fanout 4 [get_ports {sumIn[59]}]
set_max_fanout 4 [get_ports {sumIn[58]}]
set_max_fanout 4 [get_ports {sumIn[57]}]
set_max_fanout 4 [get_ports {sumIn[56]}]
set_max_fanout 4 [get_ports {sumIn[55]}]
set_max_fanout 4 [get_ports {sumIn[54]}]
set_max_fanout 4 [get_ports {sumIn[53]}]
set_max_fanout 4 [get_ports {sumIn[52]}]
set_max_fanout 4 [get_ports {sumIn[51]}]
set_max_fanout 4 [get_ports {sumIn[50]}]
set_max_fanout 4 [get_ports {sumIn[49]}]
set_max_fanout 4 [get_ports {sumIn[48]}]
set_max_fanout 4 [get_ports {sumIn[47]}]
set_max_fanout 4 [get_ports {sumIn[46]}]
set_max_fanout 4 [get_ports {sumIn[45]}]
set_max_fanout 4 [get_ports {sumIn[44]}]
set_max_fanout 4 [get_ports {sumIn[43]}]
set_max_fanout 4 [get_ports {sumIn[42]}]
set_max_fanout 4 [get_ports {sumIn[41]}]
set_max_fanout 4 [get_ports {sumIn[40]}]
set_max_fanout 4 [get_ports {sumIn[39]}]
set_max_fanout 4 [get_ports {sumIn[38]}]
set_max_fanout 4 [get_ports {sumIn[37]}]
set_max_fanout 4 [get_ports {sumIn[36]}]
set_max_fanout 4 [get_ports {sumIn[35]}]
set_max_fanout 4 [get_ports {sumIn[34]}]
set_max_fanout 4 [get_ports {sumIn[33]}]
set_max_fanout 4 [get_ports {sumIn[32]}]
set_max_fanout 4 [get_ports {sumIn[31]}]
set_max_fanout 4 [get_ports {sumIn[30]}]
set_max_fanout 4 [get_ports {sumIn[29]}]
set_max_fanout 4 [get_ports {sumIn[28]}]
set_max_fanout 4 [get_ports {sumIn[27]}]
set_max_fanout 4 [get_ports {sumIn[26]}]
set_max_fanout 4 [get_ports {sumIn[25]}]
set_max_fanout 4 [get_ports {sumIn[24]}]
set_max_fanout 4 [get_ports {sumIn[23]}]
set_max_fanout 4 [get_ports {sumIn[22]}]
set_max_fanout 4 [get_ports {sumIn[21]}]
set_max_fanout 4 [get_ports {sumIn[20]}]
set_max_fanout 4 [get_ports {sumIn[19]}]
set_max_fanout 4 [get_ports {sumIn[18]}]
set_max_fanout 4 [get_ports {sumIn[17]}]
set_max_fanout 4 [get_ports {sumIn[16]}]
set_max_fanout 4 [get_ports {sumIn[15]}]
set_max_fanout 4 [get_ports {sumIn[14]}]
set_max_fanout 4 [get_ports {sumIn[13]}]
set_max_fanout 4 [get_ports {sumIn[12]}]
set_max_fanout 4 [get_ports {sumIn[11]}]
set_max_fanout 4 [get_ports {sumIn[10]}]
set_max_fanout 4 [get_ports {sumIn[9]}]
set_max_fanout 4 [get_ports {sumIn[8]}]
set_max_fanout 4 [get_ports {sumIn[7]}]
set_max_fanout 4 [get_ports {sumIn[6]}]
set_max_fanout 4 [get_ports {sumIn[5]}]
set_max_fanout 4 [get_ports {sumIn[4]}]
set_max_fanout 4 [get_ports {sumIn[3]}]
set_max_fanout 4 [get_ports {sumIn[2]}]
set_max_fanout 4 [get_ports {sumIn[1]}]
set_max_fanout 4 [get_ports {sumIn[0]}]
