###################################################################

# Created by write_sdc on Thu Dec 20 11:55:54 2018

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_max_area 0
set_driving_cell -lib_cell INVX1TS [get_ports writeEnable]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {NodeSelect[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[159]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[158]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[157]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[156]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[155]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[154]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[153]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[152]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[151]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[150]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[149]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[148]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[147]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[146]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[145]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[144]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[143]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[142]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[141]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[140]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[139]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[138]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[137]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[136]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[135]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[134]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[133]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[132]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[131]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[130]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[129]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[128]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[127]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[126]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[125]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[124]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[123]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[122]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[121]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[120]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[119]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[118]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[117]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[116]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[115]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[114]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[113]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[112]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[111]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[110]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[109]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[108]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[107]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[106]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[105]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[104]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[103]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[102]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[101]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[100]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[99]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[98]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[97]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[96]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[95]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[94]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[93]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[92]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[91]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[90]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[89]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[88]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[87]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[86]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[85]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[84]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[83]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[82]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[81]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[80]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[79]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[78]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[77]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[76]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[75]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[74]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[73]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[72]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[71]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[70]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[69]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[68]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[67]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[66]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[65]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[64]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[63]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[62]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[61]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[60]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[59]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[58]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[57]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[56]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[55]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[54]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[53]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[52]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[51]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[50]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[49]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[48]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[47]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[46]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[45]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[44]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[43]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[42]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[41]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[40]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[39]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[38]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[37]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[36]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[35]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[34]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[33]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[32]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[31]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[30]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[29]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[28]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[27]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[26]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[25]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[24]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[23]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[22]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[21]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[20]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[19]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[18]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[17]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[16]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[0]}]
set_load -pin_load 0.005 [get_ports {readOut[159]}]
set_load -pin_load 0.005 [get_ports {readOut[158]}]
set_load -pin_load 0.005 [get_ports {readOut[157]}]
set_load -pin_load 0.005 [get_ports {readOut[156]}]
set_load -pin_load 0.005 [get_ports {readOut[155]}]
set_load -pin_load 0.005 [get_ports {readOut[154]}]
set_load -pin_load 0.005 [get_ports {readOut[153]}]
set_load -pin_load 0.005 [get_ports {readOut[152]}]
set_load -pin_load 0.005 [get_ports {readOut[151]}]
set_load -pin_load 0.005 [get_ports {readOut[150]}]
set_load -pin_load 0.005 [get_ports {readOut[149]}]
set_load -pin_load 0.005 [get_ports {readOut[148]}]
set_load -pin_load 0.005 [get_ports {readOut[147]}]
set_load -pin_load 0.005 [get_ports {readOut[146]}]
set_load -pin_load 0.005 [get_ports {readOut[145]}]
set_load -pin_load 0.005 [get_ports {readOut[144]}]
set_load -pin_load 0.005 [get_ports {readOut[143]}]
set_load -pin_load 0.005 [get_ports {readOut[142]}]
set_load -pin_load 0.005 [get_ports {readOut[141]}]
set_load -pin_load 0.005 [get_ports {readOut[140]}]
set_load -pin_load 0.005 [get_ports {readOut[139]}]
set_load -pin_load 0.005 [get_ports {readOut[138]}]
set_load -pin_load 0.005 [get_ports {readOut[137]}]
set_load -pin_load 0.005 [get_ports {readOut[136]}]
set_load -pin_load 0.005 [get_ports {readOut[135]}]
set_load -pin_load 0.005 [get_ports {readOut[134]}]
set_load -pin_load 0.005 [get_ports {readOut[133]}]
set_load -pin_load 0.005 [get_ports {readOut[132]}]
set_load -pin_load 0.005 [get_ports {readOut[131]}]
set_load -pin_load 0.005 [get_ports {readOut[130]}]
set_load -pin_load 0.005 [get_ports {readOut[129]}]
set_load -pin_load 0.005 [get_ports {readOut[128]}]
set_load -pin_load 0.005 [get_ports {readOut[127]}]
set_load -pin_load 0.005 [get_ports {readOut[126]}]
set_load -pin_load 0.005 [get_ports {readOut[125]}]
set_load -pin_load 0.005 [get_ports {readOut[124]}]
set_load -pin_load 0.005 [get_ports {readOut[123]}]
set_load -pin_load 0.005 [get_ports {readOut[122]}]
set_load -pin_load 0.005 [get_ports {readOut[121]}]
set_load -pin_load 0.005 [get_ports {readOut[120]}]
set_load -pin_load 0.005 [get_ports {readOut[119]}]
set_load -pin_load 0.005 [get_ports {readOut[118]}]
set_load -pin_load 0.005 [get_ports {readOut[117]}]
set_load -pin_load 0.005 [get_ports {readOut[116]}]
set_load -pin_load 0.005 [get_ports {readOut[115]}]
set_load -pin_load 0.005 [get_ports {readOut[114]}]
set_load -pin_load 0.005 [get_ports {readOut[113]}]
set_load -pin_load 0.005 [get_ports {readOut[112]}]
set_load -pin_load 0.005 [get_ports {readOut[111]}]
set_load -pin_load 0.005 [get_ports {readOut[110]}]
set_load -pin_load 0.005 [get_ports {readOut[109]}]
set_load -pin_load 0.005 [get_ports {readOut[108]}]
set_load -pin_load 0.005 [get_ports {readOut[107]}]
set_load -pin_load 0.005 [get_ports {readOut[106]}]
set_load -pin_load 0.005 [get_ports {readOut[105]}]
set_load -pin_load 0.005 [get_ports {readOut[104]}]
set_load -pin_load 0.005 [get_ports {readOut[103]}]
set_load -pin_load 0.005 [get_ports {readOut[102]}]
set_load -pin_load 0.005 [get_ports {readOut[101]}]
set_load -pin_load 0.005 [get_ports {readOut[100]}]
set_load -pin_load 0.005 [get_ports {readOut[99]}]
set_load -pin_load 0.005 [get_ports {readOut[98]}]
set_load -pin_load 0.005 [get_ports {readOut[97]}]
set_load -pin_load 0.005 [get_ports {readOut[96]}]
set_load -pin_load 0.005 [get_ports {readOut[95]}]
set_load -pin_load 0.005 [get_ports {readOut[94]}]
set_load -pin_load 0.005 [get_ports {readOut[93]}]
set_load -pin_load 0.005 [get_ports {readOut[92]}]
set_load -pin_load 0.005 [get_ports {readOut[91]}]
set_load -pin_load 0.005 [get_ports {readOut[90]}]
set_load -pin_load 0.005 [get_ports {readOut[89]}]
set_load -pin_load 0.005 [get_ports {readOut[88]}]
set_load -pin_load 0.005 [get_ports {readOut[87]}]
set_load -pin_load 0.005 [get_ports {readOut[86]}]
set_load -pin_load 0.005 [get_ports {readOut[85]}]
set_load -pin_load 0.005 [get_ports {readOut[84]}]
set_load -pin_load 0.005 [get_ports {readOut[83]}]
set_load -pin_load 0.005 [get_ports {readOut[82]}]
set_load -pin_load 0.005 [get_ports {readOut[81]}]
set_load -pin_load 0.005 [get_ports {readOut[80]}]
set_load -pin_load 0.005 [get_ports {readOut[79]}]
set_load -pin_load 0.005 [get_ports {readOut[78]}]
set_load -pin_load 0.005 [get_ports {readOut[77]}]
set_load -pin_load 0.005 [get_ports {readOut[76]}]
set_load -pin_load 0.005 [get_ports {readOut[75]}]
set_load -pin_load 0.005 [get_ports {readOut[74]}]
set_load -pin_load 0.005 [get_ports {readOut[73]}]
set_load -pin_load 0.005 [get_ports {readOut[72]}]
set_load -pin_load 0.005 [get_ports {readOut[71]}]
set_load -pin_load 0.005 [get_ports {readOut[70]}]
set_load -pin_load 0.005 [get_ports {readOut[69]}]
set_load -pin_load 0.005 [get_ports {readOut[68]}]
set_load -pin_load 0.005 [get_ports {readOut[67]}]
set_load -pin_load 0.005 [get_ports {readOut[66]}]
set_load -pin_load 0.005 [get_ports {readOut[65]}]
set_load -pin_load 0.005 [get_ports {readOut[64]}]
set_load -pin_load 0.005 [get_ports {readOut[63]}]
set_load -pin_load 0.005 [get_ports {readOut[62]}]
set_load -pin_load 0.005 [get_ports {readOut[61]}]
set_load -pin_load 0.005 [get_ports {readOut[60]}]
set_load -pin_load 0.005 [get_ports {readOut[59]}]
set_load -pin_load 0.005 [get_ports {readOut[58]}]
set_load -pin_load 0.005 [get_ports {readOut[57]}]
set_load -pin_load 0.005 [get_ports {readOut[56]}]
set_load -pin_load 0.005 [get_ports {readOut[55]}]
set_load -pin_load 0.005 [get_ports {readOut[54]}]
set_load -pin_load 0.005 [get_ports {readOut[53]}]
set_load -pin_load 0.005 [get_ports {readOut[52]}]
set_load -pin_load 0.005 [get_ports {readOut[51]}]
set_load -pin_load 0.005 [get_ports {readOut[50]}]
set_load -pin_load 0.005 [get_ports {readOut[49]}]
set_load -pin_load 0.005 [get_ports {readOut[48]}]
set_load -pin_load 0.005 [get_ports {readOut[47]}]
set_load -pin_load 0.005 [get_ports {readOut[46]}]
set_load -pin_load 0.005 [get_ports {readOut[45]}]
set_load -pin_load 0.005 [get_ports {readOut[44]}]
set_load -pin_load 0.005 [get_ports {readOut[43]}]
set_load -pin_load 0.005 [get_ports {readOut[42]}]
set_load -pin_load 0.005 [get_ports {readOut[41]}]
set_load -pin_load 0.005 [get_ports {readOut[40]}]
set_load -pin_load 0.005 [get_ports {readOut[39]}]
set_load -pin_load 0.005 [get_ports {readOut[38]}]
set_load -pin_load 0.005 [get_ports {readOut[37]}]
set_load -pin_load 0.005 [get_ports {readOut[36]}]
set_load -pin_load 0.005 [get_ports {readOut[35]}]
set_load -pin_load 0.005 [get_ports {readOut[34]}]
set_load -pin_load 0.005 [get_ports {readOut[33]}]
set_load -pin_load 0.005 [get_ports {readOut[32]}]
set_load -pin_load 0.005 [get_ports {readOut[31]}]
set_load -pin_load 0.005 [get_ports {readOut[30]}]
set_load -pin_load 0.005 [get_ports {readOut[29]}]
set_load -pin_load 0.005 [get_ports {readOut[28]}]
set_load -pin_load 0.005 [get_ports {readOut[27]}]
set_load -pin_load 0.005 [get_ports {readOut[26]}]
set_load -pin_load 0.005 [get_ports {readOut[25]}]
set_load -pin_load 0.005 [get_ports {readOut[24]}]
set_load -pin_load 0.005 [get_ports {readOut[23]}]
set_load -pin_load 0.005 [get_ports {readOut[22]}]
set_load -pin_load 0.005 [get_ports {readOut[21]}]
set_load -pin_load 0.005 [get_ports {readOut[20]}]
set_load -pin_load 0.005 [get_ports {readOut[19]}]
set_load -pin_load 0.005 [get_ports {readOut[18]}]
set_load -pin_load 0.005 [get_ports {readOut[17]}]
set_load -pin_load 0.005 [get_ports {readOut[16]}]
set_load -pin_load 0.005 [get_ports {readOut[15]}]
set_load -pin_load 0.005 [get_ports {readOut[14]}]
set_load -pin_load 0.005 [get_ports {readOut[13]}]
set_load -pin_load 0.005 [get_ports {readOut[12]}]
set_load -pin_load 0.005 [get_ports {readOut[11]}]
set_load -pin_load 0.005 [get_ports {readOut[10]}]
set_load -pin_load 0.005 [get_ports {readOut[9]}]
set_load -pin_load 0.005 [get_ports {readOut[8]}]
set_load -pin_load 0.005 [get_ports {readOut[7]}]
set_load -pin_load 0.005 [get_ports {readOut[6]}]
set_load -pin_load 0.005 [get_ports {readOut[5]}]
set_load -pin_load 0.005 [get_ports {readOut[4]}]
set_load -pin_load 0.005 [get_ports {readOut[3]}]
set_load -pin_load 0.005 [get_ports {readOut[2]}]
set_load -pin_load 0.005 [get_ports {readOut[1]}]
set_load -pin_load 0.005 [get_ports {readOut[0]}]
set_max_capacitance 0.005 [get_ports writeEnable]
set_max_capacitance 0.005 [get_ports {NodeSelect[9]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[8]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[7]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[6]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[5]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[4]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[3]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[2]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[1]}]
set_max_capacitance 0.005 [get_ports {NodeSelect[0]}]
set_max_capacitance 0.005 [get_ports {writeIn[159]}]
set_max_capacitance 0.005 [get_ports {writeIn[158]}]
set_max_capacitance 0.005 [get_ports {writeIn[157]}]
set_max_capacitance 0.005 [get_ports {writeIn[156]}]
set_max_capacitance 0.005 [get_ports {writeIn[155]}]
set_max_capacitance 0.005 [get_ports {writeIn[154]}]
set_max_capacitance 0.005 [get_ports {writeIn[153]}]
set_max_capacitance 0.005 [get_ports {writeIn[152]}]
set_max_capacitance 0.005 [get_ports {writeIn[151]}]
set_max_capacitance 0.005 [get_ports {writeIn[150]}]
set_max_capacitance 0.005 [get_ports {writeIn[149]}]
set_max_capacitance 0.005 [get_ports {writeIn[148]}]
set_max_capacitance 0.005 [get_ports {writeIn[147]}]
set_max_capacitance 0.005 [get_ports {writeIn[146]}]
set_max_capacitance 0.005 [get_ports {writeIn[145]}]
set_max_capacitance 0.005 [get_ports {writeIn[144]}]
set_max_capacitance 0.005 [get_ports {writeIn[143]}]
set_max_capacitance 0.005 [get_ports {writeIn[142]}]
set_max_capacitance 0.005 [get_ports {writeIn[141]}]
set_max_capacitance 0.005 [get_ports {writeIn[140]}]
set_max_capacitance 0.005 [get_ports {writeIn[139]}]
set_max_capacitance 0.005 [get_ports {writeIn[138]}]
set_max_capacitance 0.005 [get_ports {writeIn[137]}]
set_max_capacitance 0.005 [get_ports {writeIn[136]}]
set_max_capacitance 0.005 [get_ports {writeIn[135]}]
set_max_capacitance 0.005 [get_ports {writeIn[134]}]
set_max_capacitance 0.005 [get_ports {writeIn[133]}]
set_max_capacitance 0.005 [get_ports {writeIn[132]}]
set_max_capacitance 0.005 [get_ports {writeIn[131]}]
set_max_capacitance 0.005 [get_ports {writeIn[130]}]
set_max_capacitance 0.005 [get_ports {writeIn[129]}]
set_max_capacitance 0.005 [get_ports {writeIn[128]}]
set_max_capacitance 0.005 [get_ports {writeIn[127]}]
set_max_capacitance 0.005 [get_ports {writeIn[126]}]
set_max_capacitance 0.005 [get_ports {writeIn[125]}]
set_max_capacitance 0.005 [get_ports {writeIn[124]}]
set_max_capacitance 0.005 [get_ports {writeIn[123]}]
set_max_capacitance 0.005 [get_ports {writeIn[122]}]
set_max_capacitance 0.005 [get_ports {writeIn[121]}]
set_max_capacitance 0.005 [get_ports {writeIn[120]}]
set_max_capacitance 0.005 [get_ports {writeIn[119]}]
set_max_capacitance 0.005 [get_ports {writeIn[118]}]
set_max_capacitance 0.005 [get_ports {writeIn[117]}]
set_max_capacitance 0.005 [get_ports {writeIn[116]}]
set_max_capacitance 0.005 [get_ports {writeIn[115]}]
set_max_capacitance 0.005 [get_ports {writeIn[114]}]
set_max_capacitance 0.005 [get_ports {writeIn[113]}]
set_max_capacitance 0.005 [get_ports {writeIn[112]}]
set_max_capacitance 0.005 [get_ports {writeIn[111]}]
set_max_capacitance 0.005 [get_ports {writeIn[110]}]
set_max_capacitance 0.005 [get_ports {writeIn[109]}]
set_max_capacitance 0.005 [get_ports {writeIn[108]}]
set_max_capacitance 0.005 [get_ports {writeIn[107]}]
set_max_capacitance 0.005 [get_ports {writeIn[106]}]
set_max_capacitance 0.005 [get_ports {writeIn[105]}]
set_max_capacitance 0.005 [get_ports {writeIn[104]}]
set_max_capacitance 0.005 [get_ports {writeIn[103]}]
set_max_capacitance 0.005 [get_ports {writeIn[102]}]
set_max_capacitance 0.005 [get_ports {writeIn[101]}]
set_max_capacitance 0.005 [get_ports {writeIn[100]}]
set_max_capacitance 0.005 [get_ports {writeIn[99]}]
set_max_capacitance 0.005 [get_ports {writeIn[98]}]
set_max_capacitance 0.005 [get_ports {writeIn[97]}]
set_max_capacitance 0.005 [get_ports {writeIn[96]}]
set_max_capacitance 0.005 [get_ports {writeIn[95]}]
set_max_capacitance 0.005 [get_ports {writeIn[94]}]
set_max_capacitance 0.005 [get_ports {writeIn[93]}]
set_max_capacitance 0.005 [get_ports {writeIn[92]}]
set_max_capacitance 0.005 [get_ports {writeIn[91]}]
set_max_capacitance 0.005 [get_ports {writeIn[90]}]
set_max_capacitance 0.005 [get_ports {writeIn[89]}]
set_max_capacitance 0.005 [get_ports {writeIn[88]}]
set_max_capacitance 0.005 [get_ports {writeIn[87]}]
set_max_capacitance 0.005 [get_ports {writeIn[86]}]
set_max_capacitance 0.005 [get_ports {writeIn[85]}]
set_max_capacitance 0.005 [get_ports {writeIn[84]}]
set_max_capacitance 0.005 [get_ports {writeIn[83]}]
set_max_capacitance 0.005 [get_ports {writeIn[82]}]
set_max_capacitance 0.005 [get_ports {writeIn[81]}]
set_max_capacitance 0.005 [get_ports {writeIn[80]}]
set_max_capacitance 0.005 [get_ports {writeIn[79]}]
set_max_capacitance 0.005 [get_ports {writeIn[78]}]
set_max_capacitance 0.005 [get_ports {writeIn[77]}]
set_max_capacitance 0.005 [get_ports {writeIn[76]}]
set_max_capacitance 0.005 [get_ports {writeIn[75]}]
set_max_capacitance 0.005 [get_ports {writeIn[74]}]
set_max_capacitance 0.005 [get_ports {writeIn[73]}]
set_max_capacitance 0.005 [get_ports {writeIn[72]}]
set_max_capacitance 0.005 [get_ports {writeIn[71]}]
set_max_capacitance 0.005 [get_ports {writeIn[70]}]
set_max_capacitance 0.005 [get_ports {writeIn[69]}]
set_max_capacitance 0.005 [get_ports {writeIn[68]}]
set_max_capacitance 0.005 [get_ports {writeIn[67]}]
set_max_capacitance 0.005 [get_ports {writeIn[66]}]
set_max_capacitance 0.005 [get_ports {writeIn[65]}]
set_max_capacitance 0.005 [get_ports {writeIn[64]}]
set_max_capacitance 0.005 [get_ports {writeIn[63]}]
set_max_capacitance 0.005 [get_ports {writeIn[62]}]
set_max_capacitance 0.005 [get_ports {writeIn[61]}]
set_max_capacitance 0.005 [get_ports {writeIn[60]}]
set_max_capacitance 0.005 [get_ports {writeIn[59]}]
set_max_capacitance 0.005 [get_ports {writeIn[58]}]
set_max_capacitance 0.005 [get_ports {writeIn[57]}]
set_max_capacitance 0.005 [get_ports {writeIn[56]}]
set_max_capacitance 0.005 [get_ports {writeIn[55]}]
set_max_capacitance 0.005 [get_ports {writeIn[54]}]
set_max_capacitance 0.005 [get_ports {writeIn[53]}]
set_max_capacitance 0.005 [get_ports {writeIn[52]}]
set_max_capacitance 0.005 [get_ports {writeIn[51]}]
set_max_capacitance 0.005 [get_ports {writeIn[50]}]
set_max_capacitance 0.005 [get_ports {writeIn[49]}]
set_max_capacitance 0.005 [get_ports {writeIn[48]}]
set_max_capacitance 0.005 [get_ports {writeIn[47]}]
set_max_capacitance 0.005 [get_ports {writeIn[46]}]
set_max_capacitance 0.005 [get_ports {writeIn[45]}]
set_max_capacitance 0.005 [get_ports {writeIn[44]}]
set_max_capacitance 0.005 [get_ports {writeIn[43]}]
set_max_capacitance 0.005 [get_ports {writeIn[42]}]
set_max_capacitance 0.005 [get_ports {writeIn[41]}]
set_max_capacitance 0.005 [get_ports {writeIn[40]}]
set_max_capacitance 0.005 [get_ports {writeIn[39]}]
set_max_capacitance 0.005 [get_ports {writeIn[38]}]
set_max_capacitance 0.005 [get_ports {writeIn[37]}]
set_max_capacitance 0.005 [get_ports {writeIn[36]}]
set_max_capacitance 0.005 [get_ports {writeIn[35]}]
set_max_capacitance 0.005 [get_ports {writeIn[34]}]
set_max_capacitance 0.005 [get_ports {writeIn[33]}]
set_max_capacitance 0.005 [get_ports {writeIn[32]}]
set_max_capacitance 0.005 [get_ports {writeIn[31]}]
set_max_capacitance 0.005 [get_ports {writeIn[30]}]
set_max_capacitance 0.005 [get_ports {writeIn[29]}]
set_max_capacitance 0.005 [get_ports {writeIn[28]}]
set_max_capacitance 0.005 [get_ports {writeIn[27]}]
set_max_capacitance 0.005 [get_ports {writeIn[26]}]
set_max_capacitance 0.005 [get_ports {writeIn[25]}]
set_max_capacitance 0.005 [get_ports {writeIn[24]}]
set_max_capacitance 0.005 [get_ports {writeIn[23]}]
set_max_capacitance 0.005 [get_ports {writeIn[22]}]
set_max_capacitance 0.005 [get_ports {writeIn[21]}]
set_max_capacitance 0.005 [get_ports {writeIn[20]}]
set_max_capacitance 0.005 [get_ports {writeIn[19]}]
set_max_capacitance 0.005 [get_ports {writeIn[18]}]
set_max_capacitance 0.005 [get_ports {writeIn[17]}]
set_max_capacitance 0.005 [get_ports {writeIn[16]}]
set_max_capacitance 0.005 [get_ports {writeIn[15]}]
set_max_capacitance 0.005 [get_ports {writeIn[14]}]
set_max_capacitance 0.005 [get_ports {writeIn[13]}]
set_max_capacitance 0.005 [get_ports {writeIn[12]}]
set_max_capacitance 0.005 [get_ports {writeIn[11]}]
set_max_capacitance 0.005 [get_ports {writeIn[10]}]
set_max_capacitance 0.005 [get_ports {writeIn[9]}]
set_max_capacitance 0.005 [get_ports {writeIn[8]}]
set_max_capacitance 0.005 [get_ports {writeIn[7]}]
set_max_capacitance 0.005 [get_ports {writeIn[6]}]
set_max_capacitance 0.005 [get_ports {writeIn[5]}]
set_max_capacitance 0.005 [get_ports {writeIn[4]}]
set_max_capacitance 0.005 [get_ports {writeIn[3]}]
set_max_capacitance 0.005 [get_ports {writeIn[2]}]
set_max_capacitance 0.005 [get_ports {writeIn[1]}]
set_max_capacitance 0.005 [get_ports {writeIn[0]}]
set_max_fanout 4 [get_ports writeEnable]
set_max_fanout 4 [get_ports {NodeSelect[9]}]
set_max_fanout 4 [get_ports {NodeSelect[8]}]
set_max_fanout 4 [get_ports {NodeSelect[7]}]
set_max_fanout 4 [get_ports {NodeSelect[6]}]
set_max_fanout 4 [get_ports {NodeSelect[5]}]
set_max_fanout 4 [get_ports {NodeSelect[4]}]
set_max_fanout 4 [get_ports {NodeSelect[3]}]
set_max_fanout 4 [get_ports {NodeSelect[2]}]
set_max_fanout 4 [get_ports {NodeSelect[1]}]
set_max_fanout 4 [get_ports {NodeSelect[0]}]
set_max_fanout 4 [get_ports {writeIn[159]}]
set_max_fanout 4 [get_ports {writeIn[158]}]
set_max_fanout 4 [get_ports {writeIn[157]}]
set_max_fanout 4 [get_ports {writeIn[156]}]
set_max_fanout 4 [get_ports {writeIn[155]}]
set_max_fanout 4 [get_ports {writeIn[154]}]
set_max_fanout 4 [get_ports {writeIn[153]}]
set_max_fanout 4 [get_ports {writeIn[152]}]
set_max_fanout 4 [get_ports {writeIn[151]}]
set_max_fanout 4 [get_ports {writeIn[150]}]
set_max_fanout 4 [get_ports {writeIn[149]}]
set_max_fanout 4 [get_ports {writeIn[148]}]
set_max_fanout 4 [get_ports {writeIn[147]}]
set_max_fanout 4 [get_ports {writeIn[146]}]
set_max_fanout 4 [get_ports {writeIn[145]}]
set_max_fanout 4 [get_ports {writeIn[144]}]
set_max_fanout 4 [get_ports {writeIn[143]}]
set_max_fanout 4 [get_ports {writeIn[142]}]
set_max_fanout 4 [get_ports {writeIn[141]}]
set_max_fanout 4 [get_ports {writeIn[140]}]
set_max_fanout 4 [get_ports {writeIn[139]}]
set_max_fanout 4 [get_ports {writeIn[138]}]
set_max_fanout 4 [get_ports {writeIn[137]}]
set_max_fanout 4 [get_ports {writeIn[136]}]
set_max_fanout 4 [get_ports {writeIn[135]}]
set_max_fanout 4 [get_ports {writeIn[134]}]
set_max_fanout 4 [get_ports {writeIn[133]}]
set_max_fanout 4 [get_ports {writeIn[132]}]
set_max_fanout 4 [get_ports {writeIn[131]}]
set_max_fanout 4 [get_ports {writeIn[130]}]
set_max_fanout 4 [get_ports {writeIn[129]}]
set_max_fanout 4 [get_ports {writeIn[128]}]
set_max_fanout 4 [get_ports {writeIn[127]}]
set_max_fanout 4 [get_ports {writeIn[126]}]
set_max_fanout 4 [get_ports {writeIn[125]}]
set_max_fanout 4 [get_ports {writeIn[124]}]
set_max_fanout 4 [get_ports {writeIn[123]}]
set_max_fanout 4 [get_ports {writeIn[122]}]
set_max_fanout 4 [get_ports {writeIn[121]}]
set_max_fanout 4 [get_ports {writeIn[120]}]
set_max_fanout 4 [get_ports {writeIn[119]}]
set_max_fanout 4 [get_ports {writeIn[118]}]
set_max_fanout 4 [get_ports {writeIn[117]}]
set_max_fanout 4 [get_ports {writeIn[116]}]
set_max_fanout 4 [get_ports {writeIn[115]}]
set_max_fanout 4 [get_ports {writeIn[114]}]
set_max_fanout 4 [get_ports {writeIn[113]}]
set_max_fanout 4 [get_ports {writeIn[112]}]
set_max_fanout 4 [get_ports {writeIn[111]}]
set_max_fanout 4 [get_ports {writeIn[110]}]
set_max_fanout 4 [get_ports {writeIn[109]}]
set_max_fanout 4 [get_ports {writeIn[108]}]
set_max_fanout 4 [get_ports {writeIn[107]}]
set_max_fanout 4 [get_ports {writeIn[106]}]
set_max_fanout 4 [get_ports {writeIn[105]}]
set_max_fanout 4 [get_ports {writeIn[104]}]
set_max_fanout 4 [get_ports {writeIn[103]}]
set_max_fanout 4 [get_ports {writeIn[102]}]
set_max_fanout 4 [get_ports {writeIn[101]}]
set_max_fanout 4 [get_ports {writeIn[100]}]
set_max_fanout 4 [get_ports {writeIn[99]}]
set_max_fanout 4 [get_ports {writeIn[98]}]
set_max_fanout 4 [get_ports {writeIn[97]}]
set_max_fanout 4 [get_ports {writeIn[96]}]
set_max_fanout 4 [get_ports {writeIn[95]}]
set_max_fanout 4 [get_ports {writeIn[94]}]
set_max_fanout 4 [get_ports {writeIn[93]}]
set_max_fanout 4 [get_ports {writeIn[92]}]
set_max_fanout 4 [get_ports {writeIn[91]}]
set_max_fanout 4 [get_ports {writeIn[90]}]
set_max_fanout 4 [get_ports {writeIn[89]}]
set_max_fanout 4 [get_ports {writeIn[88]}]
set_max_fanout 4 [get_ports {writeIn[87]}]
set_max_fanout 4 [get_ports {writeIn[86]}]
set_max_fanout 4 [get_ports {writeIn[85]}]
set_max_fanout 4 [get_ports {writeIn[84]}]
set_max_fanout 4 [get_ports {writeIn[83]}]
set_max_fanout 4 [get_ports {writeIn[82]}]
set_max_fanout 4 [get_ports {writeIn[81]}]
set_max_fanout 4 [get_ports {writeIn[80]}]
set_max_fanout 4 [get_ports {writeIn[79]}]
set_max_fanout 4 [get_ports {writeIn[78]}]
set_max_fanout 4 [get_ports {writeIn[77]}]
set_max_fanout 4 [get_ports {writeIn[76]}]
set_max_fanout 4 [get_ports {writeIn[75]}]
set_max_fanout 4 [get_ports {writeIn[74]}]
set_max_fanout 4 [get_ports {writeIn[73]}]
set_max_fanout 4 [get_ports {writeIn[72]}]
set_max_fanout 4 [get_ports {writeIn[71]}]
set_max_fanout 4 [get_ports {writeIn[70]}]
set_max_fanout 4 [get_ports {writeIn[69]}]
set_max_fanout 4 [get_ports {writeIn[68]}]
set_max_fanout 4 [get_ports {writeIn[67]}]
set_max_fanout 4 [get_ports {writeIn[66]}]
set_max_fanout 4 [get_ports {writeIn[65]}]
set_max_fanout 4 [get_ports {writeIn[64]}]
set_max_fanout 4 [get_ports {writeIn[63]}]
set_max_fanout 4 [get_ports {writeIn[62]}]
set_max_fanout 4 [get_ports {writeIn[61]}]
set_max_fanout 4 [get_ports {writeIn[60]}]
set_max_fanout 4 [get_ports {writeIn[59]}]
set_max_fanout 4 [get_ports {writeIn[58]}]
set_max_fanout 4 [get_ports {writeIn[57]}]
set_max_fanout 4 [get_ports {writeIn[56]}]
set_max_fanout 4 [get_ports {writeIn[55]}]
set_max_fanout 4 [get_ports {writeIn[54]}]
set_max_fanout 4 [get_ports {writeIn[53]}]
set_max_fanout 4 [get_ports {writeIn[52]}]
set_max_fanout 4 [get_ports {writeIn[51]}]
set_max_fanout 4 [get_ports {writeIn[50]}]
set_max_fanout 4 [get_ports {writeIn[49]}]
set_max_fanout 4 [get_ports {writeIn[48]}]
set_max_fanout 4 [get_ports {writeIn[47]}]
set_max_fanout 4 [get_ports {writeIn[46]}]
set_max_fanout 4 [get_ports {writeIn[45]}]
set_max_fanout 4 [get_ports {writeIn[44]}]
set_max_fanout 4 [get_ports {writeIn[43]}]
set_max_fanout 4 [get_ports {writeIn[42]}]
set_max_fanout 4 [get_ports {writeIn[41]}]
set_max_fanout 4 [get_ports {writeIn[40]}]
set_max_fanout 4 [get_ports {writeIn[39]}]
set_max_fanout 4 [get_ports {writeIn[38]}]
set_max_fanout 4 [get_ports {writeIn[37]}]
set_max_fanout 4 [get_ports {writeIn[36]}]
set_max_fanout 4 [get_ports {writeIn[35]}]
set_max_fanout 4 [get_ports {writeIn[34]}]
set_max_fanout 4 [get_ports {writeIn[33]}]
set_max_fanout 4 [get_ports {writeIn[32]}]
set_max_fanout 4 [get_ports {writeIn[31]}]
set_max_fanout 4 [get_ports {writeIn[30]}]
set_max_fanout 4 [get_ports {writeIn[29]}]
set_max_fanout 4 [get_ports {writeIn[28]}]
set_max_fanout 4 [get_ports {writeIn[27]}]
set_max_fanout 4 [get_ports {writeIn[26]}]
set_max_fanout 4 [get_ports {writeIn[25]}]
set_max_fanout 4 [get_ports {writeIn[24]}]
set_max_fanout 4 [get_ports {writeIn[23]}]
set_max_fanout 4 [get_ports {writeIn[22]}]
set_max_fanout 4 [get_ports {writeIn[21]}]
set_max_fanout 4 [get_ports {writeIn[20]}]
set_max_fanout 4 [get_ports {writeIn[19]}]
set_max_fanout 4 [get_ports {writeIn[18]}]
set_max_fanout 4 [get_ports {writeIn[17]}]
set_max_fanout 4 [get_ports {writeIn[16]}]
set_max_fanout 4 [get_ports {writeIn[15]}]
set_max_fanout 4 [get_ports {writeIn[14]}]
set_max_fanout 4 [get_ports {writeIn[13]}]
set_max_fanout 4 [get_ports {writeIn[12]}]
set_max_fanout 4 [get_ports {writeIn[11]}]
set_max_fanout 4 [get_ports {writeIn[10]}]
set_max_fanout 4 [get_ports {writeIn[9]}]
set_max_fanout 4 [get_ports {writeIn[8]}]
set_max_fanout 4 [get_ports {writeIn[7]}]
set_max_fanout 4 [get_ports {writeIn[6]}]
set_max_fanout 4 [get_ports {writeIn[5]}]
set_max_fanout 4 [get_ports {writeIn[4]}]
set_max_fanout 4 [get_ports {writeIn[3]}]
set_max_fanout 4 [get_ports {writeIn[2]}]
set_max_fanout 4 [get_ports {writeIn[1]}]
set_max_fanout 4 [get_ports {writeIn[0]}]
