###################################################################

# Created by write_sdc on Wed Dec 19 17:22:13 2018

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_max_area 0
set_driving_cell -lib_cell INVX1TS [get_ports clk]
set_driving_cell -lib_cell INVX1TS [get_ports clr]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2In[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2In[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2In[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2In[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[59]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[58]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[57]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[56]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[55]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[54]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[53]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[52]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[51]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[50]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[49]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[48]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[47]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[46]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[45]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[44]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[43]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[42]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[41]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[40]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[39]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[38]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[37]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[36]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[35]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[34]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[33]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[32]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[31]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[30]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[29]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[28]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[27]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[26]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[25]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[24]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[23]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[22]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[21]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[20]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[19]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[18]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[17]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[16]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {weightsIn[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[59]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[58]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[57]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[56]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[55]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[54]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[53]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[52]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[51]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[50]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[49]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[48]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[47]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[46]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[45]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[44]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[43]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[42]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[41]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[40]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[39]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[38]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[37]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[36]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[35]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[34]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[33]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[32]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[31]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[30]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[29]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[28]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[27]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[26]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[25]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[24]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[23]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[22]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[21]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[20]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[19]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[18]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[17]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[16]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {biasesIn[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports biasWriteEnable]
set_load -pin_load 0.005 [get_ports {sumOut[99]}]
set_load -pin_load 0.005 [get_ports {sumOut[98]}]
set_load -pin_load 0.005 [get_ports {sumOut[97]}]
set_load -pin_load 0.005 [get_ports {sumOut[96]}]
set_load -pin_load 0.005 [get_ports {sumOut[95]}]
set_load -pin_load 0.005 [get_ports {sumOut[94]}]
set_load -pin_load 0.005 [get_ports {sumOut[93]}]
set_load -pin_load 0.005 [get_ports {sumOut[92]}]
set_load -pin_load 0.005 [get_ports {sumOut[91]}]
set_load -pin_load 0.005 [get_ports {sumOut[90]}]
set_load -pin_load 0.005 [get_ports {sumOut[89]}]
set_load -pin_load 0.005 [get_ports {sumOut[88]}]
set_load -pin_load 0.005 [get_ports {sumOut[87]}]
set_load -pin_load 0.005 [get_ports {sumOut[86]}]
set_load -pin_load 0.005 [get_ports {sumOut[85]}]
set_load -pin_load 0.005 [get_ports {sumOut[84]}]
set_load -pin_load 0.005 [get_ports {sumOut[83]}]
set_load -pin_load 0.005 [get_ports {sumOut[82]}]
set_load -pin_load 0.005 [get_ports {sumOut[81]}]
set_load -pin_load 0.005 [get_ports {sumOut[80]}]
set_load -pin_load 0.005 [get_ports {sumOut[79]}]
set_load -pin_load 0.005 [get_ports {sumOut[78]}]
set_load -pin_load 0.005 [get_ports {sumOut[77]}]
set_load -pin_load 0.005 [get_ports {sumOut[76]}]
set_load -pin_load 0.005 [get_ports {sumOut[75]}]
set_load -pin_load 0.005 [get_ports {sumOut[74]}]
set_load -pin_load 0.005 [get_ports {sumOut[73]}]
set_load -pin_load 0.005 [get_ports {sumOut[72]}]
set_load -pin_load 0.005 [get_ports {sumOut[71]}]
set_load -pin_load 0.005 [get_ports {sumOut[70]}]
set_load -pin_load 0.005 [get_ports {sumOut[69]}]
set_load -pin_load 0.005 [get_ports {sumOut[68]}]
set_load -pin_load 0.005 [get_ports {sumOut[67]}]
set_load -pin_load 0.005 [get_ports {sumOut[66]}]
set_load -pin_load 0.005 [get_ports {sumOut[65]}]
set_load -pin_load 0.005 [get_ports {sumOut[64]}]
set_load -pin_load 0.005 [get_ports {sumOut[63]}]
set_load -pin_load 0.005 [get_ports {sumOut[62]}]
set_load -pin_load 0.005 [get_ports {sumOut[61]}]
set_load -pin_load 0.005 [get_ports {sumOut[60]}]
set_load -pin_load 0.005 [get_ports {sumOut[59]}]
set_load -pin_load 0.005 [get_ports {sumOut[58]}]
set_load -pin_load 0.005 [get_ports {sumOut[57]}]
set_load -pin_load 0.005 [get_ports {sumOut[56]}]
set_load -pin_load 0.005 [get_ports {sumOut[55]}]
set_load -pin_load 0.005 [get_ports {sumOut[54]}]
set_load -pin_load 0.005 [get_ports {sumOut[53]}]
set_load -pin_load 0.005 [get_ports {sumOut[52]}]
set_load -pin_load 0.005 [get_ports {sumOut[51]}]
set_load -pin_load 0.005 [get_ports {sumOut[50]}]
set_load -pin_load 0.005 [get_ports {sumOut[49]}]
set_load -pin_load 0.005 [get_ports {sumOut[48]}]
set_load -pin_load 0.005 [get_ports {sumOut[47]}]
set_load -pin_load 0.005 [get_ports {sumOut[46]}]
set_load -pin_load 0.005 [get_ports {sumOut[45]}]
set_load -pin_load 0.005 [get_ports {sumOut[44]}]
set_load -pin_load 0.005 [get_ports {sumOut[43]}]
set_load -pin_load 0.005 [get_ports {sumOut[42]}]
set_load -pin_load 0.005 [get_ports {sumOut[41]}]
set_load -pin_load 0.005 [get_ports {sumOut[40]}]
set_load -pin_load 0.005 [get_ports {sumOut[39]}]
set_load -pin_load 0.005 [get_ports {sumOut[38]}]
set_load -pin_load 0.005 [get_ports {sumOut[37]}]
set_load -pin_load 0.005 [get_ports {sumOut[36]}]
set_load -pin_load 0.005 [get_ports {sumOut[35]}]
set_load -pin_load 0.005 [get_ports {sumOut[34]}]
set_load -pin_load 0.005 [get_ports {sumOut[33]}]
set_load -pin_load 0.005 [get_ports {sumOut[32]}]
set_load -pin_load 0.005 [get_ports {sumOut[31]}]
set_load -pin_load 0.005 [get_ports {sumOut[30]}]
set_load -pin_load 0.005 [get_ports {sumOut[29]}]
set_load -pin_load 0.005 [get_ports {sumOut[28]}]
set_load -pin_load 0.005 [get_ports {sumOut[27]}]
set_load -pin_load 0.005 [get_ports {sumOut[26]}]
set_load -pin_load 0.005 [get_ports {sumOut[25]}]
set_load -pin_load 0.005 [get_ports {sumOut[24]}]
set_load -pin_load 0.005 [get_ports {sumOut[23]}]
set_load -pin_load 0.005 [get_ports {sumOut[22]}]
set_load -pin_load 0.005 [get_ports {sumOut[21]}]
set_load -pin_load 0.005 [get_ports {sumOut[20]}]
set_load -pin_load 0.005 [get_ports {sumOut[19]}]
set_load -pin_load 0.005 [get_ports {sumOut[18]}]
set_load -pin_load 0.005 [get_ports {sumOut[17]}]
set_load -pin_load 0.005 [get_ports {sumOut[16]}]
set_load -pin_load 0.005 [get_ports {sumOut[15]}]
set_load -pin_load 0.005 [get_ports {sumOut[14]}]
set_load -pin_load 0.005 [get_ports {sumOut[13]}]
set_load -pin_load 0.005 [get_ports {sumOut[12]}]
set_load -pin_load 0.005 [get_ports {sumOut[11]}]
set_load -pin_load 0.005 [get_ports {sumOut[10]}]
set_load -pin_load 0.005 [get_ports {sumOut[9]}]
set_load -pin_load 0.005 [get_ports {sumOut[8]}]
set_load -pin_load 0.005 [get_ports {sumOut[7]}]
set_load -pin_load 0.005 [get_ports {sumOut[6]}]
set_load -pin_load 0.005 [get_ports {sumOut[5]}]
set_load -pin_load 0.005 [get_ports {sumOut[4]}]
set_load -pin_load 0.005 [get_ports {sumOut[3]}]
set_load -pin_load 0.005 [get_ports {sumOut[2]}]
set_load -pin_load 0.005 [get_ports {sumOut[1]}]
set_load -pin_load 0.005 [get_ports {sumOut[0]}]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports clr]
set_max_capacitance 0.005 [get_ports {layer2In[3]}]
set_max_capacitance 0.005 [get_ports {layer2In[2]}]
set_max_capacitance 0.005 [get_ports {layer2In[1]}]
set_max_capacitance 0.005 [get_ports {layer2In[0]}]
set_max_capacitance 0.005 [get_ports {weightsIn[59]}]
set_max_capacitance 0.005 [get_ports {weightsIn[58]}]
set_max_capacitance 0.005 [get_ports {weightsIn[57]}]
set_max_capacitance 0.005 [get_ports {weightsIn[56]}]
set_max_capacitance 0.005 [get_ports {weightsIn[55]}]
set_max_capacitance 0.005 [get_ports {weightsIn[54]}]
set_max_capacitance 0.005 [get_ports {weightsIn[53]}]
set_max_capacitance 0.005 [get_ports {weightsIn[52]}]
set_max_capacitance 0.005 [get_ports {weightsIn[51]}]
set_max_capacitance 0.005 [get_ports {weightsIn[50]}]
set_max_capacitance 0.005 [get_ports {weightsIn[49]}]
set_max_capacitance 0.005 [get_ports {weightsIn[48]}]
set_max_capacitance 0.005 [get_ports {weightsIn[47]}]
set_max_capacitance 0.005 [get_ports {weightsIn[46]}]
set_max_capacitance 0.005 [get_ports {weightsIn[45]}]
set_max_capacitance 0.005 [get_ports {weightsIn[44]}]
set_max_capacitance 0.005 [get_ports {weightsIn[43]}]
set_max_capacitance 0.005 [get_ports {weightsIn[42]}]
set_max_capacitance 0.005 [get_ports {weightsIn[41]}]
set_max_capacitance 0.005 [get_ports {weightsIn[40]}]
set_max_capacitance 0.005 [get_ports {weightsIn[39]}]
set_max_capacitance 0.005 [get_ports {weightsIn[38]}]
set_max_capacitance 0.005 [get_ports {weightsIn[37]}]
set_max_capacitance 0.005 [get_ports {weightsIn[36]}]
set_max_capacitance 0.005 [get_ports {weightsIn[35]}]
set_max_capacitance 0.005 [get_ports {weightsIn[34]}]
set_max_capacitance 0.005 [get_ports {weightsIn[33]}]
set_max_capacitance 0.005 [get_ports {weightsIn[32]}]
set_max_capacitance 0.005 [get_ports {weightsIn[31]}]
set_max_capacitance 0.005 [get_ports {weightsIn[30]}]
set_max_capacitance 0.005 [get_ports {weightsIn[29]}]
set_max_capacitance 0.005 [get_ports {weightsIn[28]}]
set_max_capacitance 0.005 [get_ports {weightsIn[27]}]
set_max_capacitance 0.005 [get_ports {weightsIn[26]}]
set_max_capacitance 0.005 [get_ports {weightsIn[25]}]
set_max_capacitance 0.005 [get_ports {weightsIn[24]}]
set_max_capacitance 0.005 [get_ports {weightsIn[23]}]
set_max_capacitance 0.005 [get_ports {weightsIn[22]}]
set_max_capacitance 0.005 [get_ports {weightsIn[21]}]
set_max_capacitance 0.005 [get_ports {weightsIn[20]}]
set_max_capacitance 0.005 [get_ports {weightsIn[19]}]
set_max_capacitance 0.005 [get_ports {weightsIn[18]}]
set_max_capacitance 0.005 [get_ports {weightsIn[17]}]
set_max_capacitance 0.005 [get_ports {weightsIn[16]}]
set_max_capacitance 0.005 [get_ports {weightsIn[15]}]
set_max_capacitance 0.005 [get_ports {weightsIn[14]}]
set_max_capacitance 0.005 [get_ports {weightsIn[13]}]
set_max_capacitance 0.005 [get_ports {weightsIn[12]}]
set_max_capacitance 0.005 [get_ports {weightsIn[11]}]
set_max_capacitance 0.005 [get_ports {weightsIn[10]}]
set_max_capacitance 0.005 [get_ports {weightsIn[9]}]
set_max_capacitance 0.005 [get_ports {weightsIn[8]}]
set_max_capacitance 0.005 [get_ports {weightsIn[7]}]
set_max_capacitance 0.005 [get_ports {weightsIn[6]}]
set_max_capacitance 0.005 [get_ports {weightsIn[5]}]
set_max_capacitance 0.005 [get_ports {weightsIn[4]}]
set_max_capacitance 0.005 [get_ports {weightsIn[3]}]
set_max_capacitance 0.005 [get_ports {weightsIn[2]}]
set_max_capacitance 0.005 [get_ports {weightsIn[1]}]
set_max_capacitance 0.005 [get_ports {weightsIn[0]}]
set_max_capacitance 0.005 [get_ports {biasesIn[59]}]
set_max_capacitance 0.005 [get_ports {biasesIn[58]}]
set_max_capacitance 0.005 [get_ports {biasesIn[57]}]
set_max_capacitance 0.005 [get_ports {biasesIn[56]}]
set_max_capacitance 0.005 [get_ports {biasesIn[55]}]
set_max_capacitance 0.005 [get_ports {biasesIn[54]}]
set_max_capacitance 0.005 [get_ports {biasesIn[53]}]
set_max_capacitance 0.005 [get_ports {biasesIn[52]}]
set_max_capacitance 0.005 [get_ports {biasesIn[51]}]
set_max_capacitance 0.005 [get_ports {biasesIn[50]}]
set_max_capacitance 0.005 [get_ports {biasesIn[49]}]
set_max_capacitance 0.005 [get_ports {biasesIn[48]}]
set_max_capacitance 0.005 [get_ports {biasesIn[47]}]
set_max_capacitance 0.005 [get_ports {biasesIn[46]}]
set_max_capacitance 0.005 [get_ports {biasesIn[45]}]
set_max_capacitance 0.005 [get_ports {biasesIn[44]}]
set_max_capacitance 0.005 [get_ports {biasesIn[43]}]
set_max_capacitance 0.005 [get_ports {biasesIn[42]}]
set_max_capacitance 0.005 [get_ports {biasesIn[41]}]
set_max_capacitance 0.005 [get_ports {biasesIn[40]}]
set_max_capacitance 0.005 [get_ports {biasesIn[39]}]
set_max_capacitance 0.005 [get_ports {biasesIn[38]}]
set_max_capacitance 0.005 [get_ports {biasesIn[37]}]
set_max_capacitance 0.005 [get_ports {biasesIn[36]}]
set_max_capacitance 0.005 [get_ports {biasesIn[35]}]
set_max_capacitance 0.005 [get_ports {biasesIn[34]}]
set_max_capacitance 0.005 [get_ports {biasesIn[33]}]
set_max_capacitance 0.005 [get_ports {biasesIn[32]}]
set_max_capacitance 0.005 [get_ports {biasesIn[31]}]
set_max_capacitance 0.005 [get_ports {biasesIn[30]}]
set_max_capacitance 0.005 [get_ports {biasesIn[29]}]
set_max_capacitance 0.005 [get_ports {biasesIn[28]}]
set_max_capacitance 0.005 [get_ports {biasesIn[27]}]
set_max_capacitance 0.005 [get_ports {biasesIn[26]}]
set_max_capacitance 0.005 [get_ports {biasesIn[25]}]
set_max_capacitance 0.005 [get_ports {biasesIn[24]}]
set_max_capacitance 0.005 [get_ports {biasesIn[23]}]
set_max_capacitance 0.005 [get_ports {biasesIn[22]}]
set_max_capacitance 0.005 [get_ports {biasesIn[21]}]
set_max_capacitance 0.005 [get_ports {biasesIn[20]}]
set_max_capacitance 0.005 [get_ports {biasesIn[19]}]
set_max_capacitance 0.005 [get_ports {biasesIn[18]}]
set_max_capacitance 0.005 [get_ports {biasesIn[17]}]
set_max_capacitance 0.005 [get_ports {biasesIn[16]}]
set_max_capacitance 0.005 [get_ports {biasesIn[15]}]
set_max_capacitance 0.005 [get_ports {biasesIn[14]}]
set_max_capacitance 0.005 [get_ports {biasesIn[13]}]
set_max_capacitance 0.005 [get_ports {biasesIn[12]}]
set_max_capacitance 0.005 [get_ports {biasesIn[11]}]
set_max_capacitance 0.005 [get_ports {biasesIn[10]}]
set_max_capacitance 0.005 [get_ports {biasesIn[9]}]
set_max_capacitance 0.005 [get_ports {biasesIn[8]}]
set_max_capacitance 0.005 [get_ports {biasesIn[7]}]
set_max_capacitance 0.005 [get_ports {biasesIn[6]}]
set_max_capacitance 0.005 [get_ports {biasesIn[5]}]
set_max_capacitance 0.005 [get_ports {biasesIn[4]}]
set_max_capacitance 0.005 [get_ports {biasesIn[3]}]
set_max_capacitance 0.005 [get_ports {biasesIn[2]}]
set_max_capacitance 0.005 [get_ports {biasesIn[1]}]
set_max_capacitance 0.005 [get_ports {biasesIn[0]}]
set_max_capacitance 0.005 [get_ports biasWriteEnable]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports clr]
set_max_fanout 4 [get_ports {layer2In[3]}]
set_max_fanout 4 [get_ports {layer2In[2]}]
set_max_fanout 4 [get_ports {layer2In[1]}]
set_max_fanout 4 [get_ports {layer2In[0]}]
set_max_fanout 4 [get_ports {weightsIn[59]}]
set_max_fanout 4 [get_ports {weightsIn[58]}]
set_max_fanout 4 [get_ports {weightsIn[57]}]
set_max_fanout 4 [get_ports {weightsIn[56]}]
set_max_fanout 4 [get_ports {weightsIn[55]}]
set_max_fanout 4 [get_ports {weightsIn[54]}]
set_max_fanout 4 [get_ports {weightsIn[53]}]
set_max_fanout 4 [get_ports {weightsIn[52]}]
set_max_fanout 4 [get_ports {weightsIn[51]}]
set_max_fanout 4 [get_ports {weightsIn[50]}]
set_max_fanout 4 [get_ports {weightsIn[49]}]
set_max_fanout 4 [get_ports {weightsIn[48]}]
set_max_fanout 4 [get_ports {weightsIn[47]}]
set_max_fanout 4 [get_ports {weightsIn[46]}]
set_max_fanout 4 [get_ports {weightsIn[45]}]
set_max_fanout 4 [get_ports {weightsIn[44]}]
set_max_fanout 4 [get_ports {weightsIn[43]}]
set_max_fanout 4 [get_ports {weightsIn[42]}]
set_max_fanout 4 [get_ports {weightsIn[41]}]
set_max_fanout 4 [get_ports {weightsIn[40]}]
set_max_fanout 4 [get_ports {weightsIn[39]}]
set_max_fanout 4 [get_ports {weightsIn[38]}]
set_max_fanout 4 [get_ports {weightsIn[37]}]
set_max_fanout 4 [get_ports {weightsIn[36]}]
set_max_fanout 4 [get_ports {weightsIn[35]}]
set_max_fanout 4 [get_ports {weightsIn[34]}]
set_max_fanout 4 [get_ports {weightsIn[33]}]
set_max_fanout 4 [get_ports {weightsIn[32]}]
set_max_fanout 4 [get_ports {weightsIn[31]}]
set_max_fanout 4 [get_ports {weightsIn[30]}]
set_max_fanout 4 [get_ports {weightsIn[29]}]
set_max_fanout 4 [get_ports {weightsIn[28]}]
set_max_fanout 4 [get_ports {weightsIn[27]}]
set_max_fanout 4 [get_ports {weightsIn[26]}]
set_max_fanout 4 [get_ports {weightsIn[25]}]
set_max_fanout 4 [get_ports {weightsIn[24]}]
set_max_fanout 4 [get_ports {weightsIn[23]}]
set_max_fanout 4 [get_ports {weightsIn[22]}]
set_max_fanout 4 [get_ports {weightsIn[21]}]
set_max_fanout 4 [get_ports {weightsIn[20]}]
set_max_fanout 4 [get_ports {weightsIn[19]}]
set_max_fanout 4 [get_ports {weightsIn[18]}]
set_max_fanout 4 [get_ports {weightsIn[17]}]
set_max_fanout 4 [get_ports {weightsIn[16]}]
set_max_fanout 4 [get_ports {weightsIn[15]}]
set_max_fanout 4 [get_ports {weightsIn[14]}]
set_max_fanout 4 [get_ports {weightsIn[13]}]
set_max_fanout 4 [get_ports {weightsIn[12]}]
set_max_fanout 4 [get_ports {weightsIn[11]}]
set_max_fanout 4 [get_ports {weightsIn[10]}]
set_max_fanout 4 [get_ports {weightsIn[9]}]
set_max_fanout 4 [get_ports {weightsIn[8]}]
set_max_fanout 4 [get_ports {weightsIn[7]}]
set_max_fanout 4 [get_ports {weightsIn[6]}]
set_max_fanout 4 [get_ports {weightsIn[5]}]
set_max_fanout 4 [get_ports {weightsIn[4]}]
set_max_fanout 4 [get_ports {weightsIn[3]}]
set_max_fanout 4 [get_ports {weightsIn[2]}]
set_max_fanout 4 [get_ports {weightsIn[1]}]
set_max_fanout 4 [get_ports {weightsIn[0]}]
set_max_fanout 4 [get_ports {biasesIn[59]}]
set_max_fanout 4 [get_ports {biasesIn[58]}]
set_max_fanout 4 [get_ports {biasesIn[57]}]
set_max_fanout 4 [get_ports {biasesIn[56]}]
set_max_fanout 4 [get_ports {biasesIn[55]}]
set_max_fanout 4 [get_ports {biasesIn[54]}]
set_max_fanout 4 [get_ports {biasesIn[53]}]
set_max_fanout 4 [get_ports {biasesIn[52]}]
set_max_fanout 4 [get_ports {biasesIn[51]}]
set_max_fanout 4 [get_ports {biasesIn[50]}]
set_max_fanout 4 [get_ports {biasesIn[49]}]
set_max_fanout 4 [get_ports {biasesIn[48]}]
set_max_fanout 4 [get_ports {biasesIn[47]}]
set_max_fanout 4 [get_ports {biasesIn[46]}]
set_max_fanout 4 [get_ports {biasesIn[45]}]
set_max_fanout 4 [get_ports {biasesIn[44]}]
set_max_fanout 4 [get_ports {biasesIn[43]}]
set_max_fanout 4 [get_ports {biasesIn[42]}]
set_max_fanout 4 [get_ports {biasesIn[41]}]
set_max_fanout 4 [get_ports {biasesIn[40]}]
set_max_fanout 4 [get_ports {biasesIn[39]}]
set_max_fanout 4 [get_ports {biasesIn[38]}]
set_max_fanout 4 [get_ports {biasesIn[37]}]
set_max_fanout 4 [get_ports {biasesIn[36]}]
set_max_fanout 4 [get_ports {biasesIn[35]}]
set_max_fanout 4 [get_ports {biasesIn[34]}]
set_max_fanout 4 [get_ports {biasesIn[33]}]
set_max_fanout 4 [get_ports {biasesIn[32]}]
set_max_fanout 4 [get_ports {biasesIn[31]}]
set_max_fanout 4 [get_ports {biasesIn[30]}]
set_max_fanout 4 [get_ports {biasesIn[29]}]
set_max_fanout 4 [get_ports {biasesIn[28]}]
set_max_fanout 4 [get_ports {biasesIn[27]}]
set_max_fanout 4 [get_ports {biasesIn[26]}]
set_max_fanout 4 [get_ports {biasesIn[25]}]
set_max_fanout 4 [get_ports {biasesIn[24]}]
set_max_fanout 4 [get_ports {biasesIn[23]}]
set_max_fanout 4 [get_ports {biasesIn[22]}]
set_max_fanout 4 [get_ports {biasesIn[21]}]
set_max_fanout 4 [get_ports {biasesIn[20]}]
set_max_fanout 4 [get_ports {biasesIn[19]}]
set_max_fanout 4 [get_ports {biasesIn[18]}]
set_max_fanout 4 [get_ports {biasesIn[17]}]
set_max_fanout 4 [get_ports {biasesIn[16]}]
set_max_fanout 4 [get_ports {biasesIn[15]}]
set_max_fanout 4 [get_ports {biasesIn[14]}]
set_max_fanout 4 [get_ports {biasesIn[13]}]
set_max_fanout 4 [get_ports {biasesIn[12]}]
set_max_fanout 4 [get_ports {biasesIn[11]}]
set_max_fanout 4 [get_ports {biasesIn[10]}]
set_max_fanout 4 [get_ports {biasesIn[9]}]
set_max_fanout 4 [get_ports {biasesIn[8]}]
set_max_fanout 4 [get_ports {biasesIn[7]}]
set_max_fanout 4 [get_ports {biasesIn[6]}]
set_max_fanout 4 [get_ports {biasesIn[5]}]
set_max_fanout 4 [get_ports {biasesIn[4]}]
set_max_fanout 4 [get_ports {biasesIn[3]}]
set_max_fanout 4 [get_ports {biasesIn[2]}]
set_max_fanout 4 [get_ports {biasesIn[1]}]
set_max_fanout 4 [get_ports {biasesIn[0]}]
set_max_fanout 4 [get_ports biasWriteEnable]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 1  -waveform {0 0.5}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.01 [get_clocks clk]
set_clock_transition -max -fall 0.01 [get_clocks clk]
set_clock_transition -min -rise 0.01 [get_clocks clk]
set_clock_transition -min -fall 0.01 [get_clocks clk]
set_input_delay -clock clk  0.05  [get_ports clr]
set_input_delay -clock clk  0.05  [get_ports {layer2In[3]}]
set_input_delay -clock clk  0.05  [get_ports {layer2In[2]}]
set_input_delay -clock clk  0.05  [get_ports {layer2In[1]}]
set_input_delay -clock clk  0.05  [get_ports {layer2In[0]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[59]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[58]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[57]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[56]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[55]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[54]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[53]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[52]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[51]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[50]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[49]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[48]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[47]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[46]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[45]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[44]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[43]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[42]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[41]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[40]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[39]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[38]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[37]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[36]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[35]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[34]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[33]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[32]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[31]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[30]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[29]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[28]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[27]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[26]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[25]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[24]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[23]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[22]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[21]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[20]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[19]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[18]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[17]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[16]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[15]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[14]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[13]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[12]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[11]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[10]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[9]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[8]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[7]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[6]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[5]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[4]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[3]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[2]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[1]}]
set_input_delay -clock clk  0.05  [get_ports {weightsIn[0]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[59]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[58]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[57]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[56]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[55]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[54]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[53]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[52]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[51]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[50]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[49]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[48]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[47]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[46]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[45]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[44]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[43]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[42]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[41]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[40]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[39]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[38]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[37]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[36]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[35]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[34]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[33]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[32]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[31]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[30]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[29]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[28]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[27]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[26]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[25]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[24]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[23]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[22]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[21]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[20]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[19]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[18]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[17]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[16]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[15]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[14]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[13]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[12]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[11]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[10]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[9]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[8]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[7]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[6]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[5]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[4]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[3]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[2]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[1]}]
set_input_delay -clock clk  0.05  [get_ports {biasesIn[0]}]
set_input_delay -clock clk  0.05  [get_ports biasWriteEnable]
set_output_delay -clock clk  0.05  [get_ports {sumOut[99]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[98]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[97]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[96]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[95]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[94]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[93]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[92]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[91]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[90]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[89]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[88]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[87]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[86]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[85]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[84]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[83]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[82]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[81]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[80]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[79]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[78]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[77]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[76]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[75]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[74]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[73]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[72]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[71]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[70]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[69]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[68]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[67]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[66]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[65]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[64]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[63]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[62]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[61]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[60]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[59]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[58]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[57]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[56]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[55]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[54]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[53]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[52]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[51]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[50]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[49]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[48]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[47]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[46]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[45]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[44]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[43]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[42]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[41]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[40]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[39]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[38]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[37]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[36]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[35]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[34]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[33]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[32]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[31]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[30]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[29]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[28]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[27]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[26]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[25]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[24]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[23]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[22]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[21]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[20]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[19]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[18]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[17]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[16]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[15]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[14]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[13]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[12]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[11]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[10]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[9]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[8]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[7]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[6]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[5]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[4]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[3]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[2]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[1]}]
set_output_delay -clock clk  0.05  [get_ports {sumOut[0]}]
