###################################################################

# Created by write_sdc on Thu Dec 20 13:02:02 2018

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_area 0
set_driving_cell -lib_cell INVX1TS [get_ports reset]
set_driving_cell -lib_cell INVX1TS [get_ports clk]
set_driving_cell -lib_cell INVX1TS [get_ports inputsReady]
set_driving_cell -lib_cell INVX1TS [get_ports outputsRecieved]
set_driving_cell -lib_cell INVX1TS [get_ports weightWriteEnable]
set_driving_cell -lib_cell INVX1TS [get_ports biasWriteEnable]
set_driving_cell -lib_cell INVX1TS [get_ports {WriteAddressSelect[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {WriteAddressSelect[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {WriteAddressSelect[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[39]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[38]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[37]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[36]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[35]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[34]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[33]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[32]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[31]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[30]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[29]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[28]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[27]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[26]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[25]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[24]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[23]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[22]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[21]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[20]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[19]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[18]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[17]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[16]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {writeIn[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[23]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[22]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[21]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[20]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[19]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[18]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[17]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[16]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {layer2Input[0]}]
set_load -pin_load 0.005 [get_ports inputsRecieved]
set_load -pin_load 0.005 [get_ports outputsReady]
set_load -pin_load 0.005 [get_ports {predictionOutput[3]}]
set_load -pin_load 0.005 [get_ports {predictionOutput[2]}]
set_load -pin_load 0.005 [get_ports {predictionOutput[1]}]
set_load -pin_load 0.005 [get_ports {predictionOutput[0]}]
set_max_capacitance 0.005 [get_ports reset]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports inputsReady]
set_max_capacitance 0.005 [get_ports outputsRecieved]
set_max_capacitance 0.005 [get_ports weightWriteEnable]
set_max_capacitance 0.005 [get_ports biasWriteEnable]
set_max_capacitance 0.005 [get_ports {WriteAddressSelect[2]}]
set_max_capacitance 0.005 [get_ports {WriteAddressSelect[1]}]
set_max_capacitance 0.005 [get_ports {WriteAddressSelect[0]}]
set_max_capacitance 0.005 [get_ports {writeIn[39]}]
set_max_capacitance 0.005 [get_ports {writeIn[38]}]
set_max_capacitance 0.005 [get_ports {writeIn[37]}]
set_max_capacitance 0.005 [get_ports {writeIn[36]}]
set_max_capacitance 0.005 [get_ports {writeIn[35]}]
set_max_capacitance 0.005 [get_ports {writeIn[34]}]
set_max_capacitance 0.005 [get_ports {writeIn[33]}]
set_max_capacitance 0.005 [get_ports {writeIn[32]}]
set_max_capacitance 0.005 [get_ports {writeIn[31]}]
set_max_capacitance 0.005 [get_ports {writeIn[30]}]
set_max_capacitance 0.005 [get_ports {writeIn[29]}]
set_max_capacitance 0.005 [get_ports {writeIn[28]}]
set_max_capacitance 0.005 [get_ports {writeIn[27]}]
set_max_capacitance 0.005 [get_ports {writeIn[26]}]
set_max_capacitance 0.005 [get_ports {writeIn[25]}]
set_max_capacitance 0.005 [get_ports {writeIn[24]}]
set_max_capacitance 0.005 [get_ports {writeIn[23]}]
set_max_capacitance 0.005 [get_ports {writeIn[22]}]
set_max_capacitance 0.005 [get_ports {writeIn[21]}]
set_max_capacitance 0.005 [get_ports {writeIn[20]}]
set_max_capacitance 0.005 [get_ports {writeIn[19]}]
set_max_capacitance 0.005 [get_ports {writeIn[18]}]
set_max_capacitance 0.005 [get_ports {writeIn[17]}]
set_max_capacitance 0.005 [get_ports {writeIn[16]}]
set_max_capacitance 0.005 [get_ports {writeIn[15]}]
set_max_capacitance 0.005 [get_ports {writeIn[14]}]
set_max_capacitance 0.005 [get_ports {writeIn[13]}]
set_max_capacitance 0.005 [get_ports {writeIn[12]}]
set_max_capacitance 0.005 [get_ports {writeIn[11]}]
set_max_capacitance 0.005 [get_ports {writeIn[10]}]
set_max_capacitance 0.005 [get_ports {writeIn[9]}]
set_max_capacitance 0.005 [get_ports {writeIn[8]}]
set_max_capacitance 0.005 [get_ports {writeIn[7]}]
set_max_capacitance 0.005 [get_ports {writeIn[6]}]
set_max_capacitance 0.005 [get_ports {writeIn[5]}]
set_max_capacitance 0.005 [get_ports {writeIn[4]}]
set_max_capacitance 0.005 [get_ports {writeIn[3]}]
set_max_capacitance 0.005 [get_ports {writeIn[2]}]
set_max_capacitance 0.005 [get_ports {writeIn[1]}]
set_max_capacitance 0.005 [get_ports {writeIn[0]}]
set_max_capacitance 0.005 [get_ports {layer2Input[23]}]
set_max_capacitance 0.005 [get_ports {layer2Input[22]}]
set_max_capacitance 0.005 [get_ports {layer2Input[21]}]
set_max_capacitance 0.005 [get_ports {layer2Input[20]}]
set_max_capacitance 0.005 [get_ports {layer2Input[19]}]
set_max_capacitance 0.005 [get_ports {layer2Input[18]}]
set_max_capacitance 0.005 [get_ports {layer2Input[17]}]
set_max_capacitance 0.005 [get_ports {layer2Input[16]}]
set_max_capacitance 0.005 [get_ports {layer2Input[15]}]
set_max_capacitance 0.005 [get_ports {layer2Input[14]}]
set_max_capacitance 0.005 [get_ports {layer2Input[13]}]
set_max_capacitance 0.005 [get_ports {layer2Input[12]}]
set_max_capacitance 0.005 [get_ports {layer2Input[11]}]
set_max_capacitance 0.005 [get_ports {layer2Input[10]}]
set_max_capacitance 0.005 [get_ports {layer2Input[9]}]
set_max_capacitance 0.005 [get_ports {layer2Input[8]}]
set_max_capacitance 0.005 [get_ports {layer2Input[7]}]
set_max_capacitance 0.005 [get_ports {layer2Input[6]}]
set_max_capacitance 0.005 [get_ports {layer2Input[5]}]
set_max_capacitance 0.005 [get_ports {layer2Input[4]}]
set_max_capacitance 0.005 [get_ports {layer2Input[3]}]
set_max_capacitance 0.005 [get_ports {layer2Input[2]}]
set_max_capacitance 0.005 [get_ports {layer2Input[1]}]
set_max_capacitance 0.005 [get_ports {layer2Input[0]}]
set_max_fanout 4 [get_ports reset]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports inputsReady]
set_max_fanout 4 [get_ports outputsRecieved]
set_max_fanout 4 [get_ports weightWriteEnable]
set_max_fanout 4 [get_ports biasWriteEnable]
set_max_fanout 4 [get_ports {WriteAddressSelect[2]}]
set_max_fanout 4 [get_ports {WriteAddressSelect[1]}]
set_max_fanout 4 [get_ports {WriteAddressSelect[0]}]
set_max_fanout 4 [get_ports {writeIn[39]}]
set_max_fanout 4 [get_ports {writeIn[38]}]
set_max_fanout 4 [get_ports {writeIn[37]}]
set_max_fanout 4 [get_ports {writeIn[36]}]
set_max_fanout 4 [get_ports {writeIn[35]}]
set_max_fanout 4 [get_ports {writeIn[34]}]
set_max_fanout 4 [get_ports {writeIn[33]}]
set_max_fanout 4 [get_ports {writeIn[32]}]
set_max_fanout 4 [get_ports {writeIn[31]}]
set_max_fanout 4 [get_ports {writeIn[30]}]
set_max_fanout 4 [get_ports {writeIn[29]}]
set_max_fanout 4 [get_ports {writeIn[28]}]
set_max_fanout 4 [get_ports {writeIn[27]}]
set_max_fanout 4 [get_ports {writeIn[26]}]
set_max_fanout 4 [get_ports {writeIn[25]}]
set_max_fanout 4 [get_ports {writeIn[24]}]
set_max_fanout 4 [get_ports {writeIn[23]}]
set_max_fanout 4 [get_ports {writeIn[22]}]
set_max_fanout 4 [get_ports {writeIn[21]}]
set_max_fanout 4 [get_ports {writeIn[20]}]
set_max_fanout 4 [get_ports {writeIn[19]}]
set_max_fanout 4 [get_ports {writeIn[18]}]
set_max_fanout 4 [get_ports {writeIn[17]}]
set_max_fanout 4 [get_ports {writeIn[16]}]
set_max_fanout 4 [get_ports {writeIn[15]}]
set_max_fanout 4 [get_ports {writeIn[14]}]
set_max_fanout 4 [get_ports {writeIn[13]}]
set_max_fanout 4 [get_ports {writeIn[12]}]
set_max_fanout 4 [get_ports {writeIn[11]}]
set_max_fanout 4 [get_ports {writeIn[10]}]
set_max_fanout 4 [get_ports {writeIn[9]}]
set_max_fanout 4 [get_ports {writeIn[8]}]
set_max_fanout 4 [get_ports {writeIn[7]}]
set_max_fanout 4 [get_ports {writeIn[6]}]
set_max_fanout 4 [get_ports {writeIn[5]}]
set_max_fanout 4 [get_ports {writeIn[4]}]
set_max_fanout 4 [get_ports {writeIn[3]}]
set_max_fanout 4 [get_ports {writeIn[2]}]
set_max_fanout 4 [get_ports {writeIn[1]}]
set_max_fanout 4 [get_ports {writeIn[0]}]
set_max_fanout 4 [get_ports {layer2Input[23]}]
set_max_fanout 4 [get_ports {layer2Input[22]}]
set_max_fanout 4 [get_ports {layer2Input[21]}]
set_max_fanout 4 [get_ports {layer2Input[20]}]
set_max_fanout 4 [get_ports {layer2Input[19]}]
set_max_fanout 4 [get_ports {layer2Input[18]}]
set_max_fanout 4 [get_ports {layer2Input[17]}]
set_max_fanout 4 [get_ports {layer2Input[16]}]
set_max_fanout 4 [get_ports {layer2Input[15]}]
set_max_fanout 4 [get_ports {layer2Input[14]}]
set_max_fanout 4 [get_ports {layer2Input[13]}]
set_max_fanout 4 [get_ports {layer2Input[12]}]
set_max_fanout 4 [get_ports {layer2Input[11]}]
set_max_fanout 4 [get_ports {layer2Input[10]}]
set_max_fanout 4 [get_ports {layer2Input[9]}]
set_max_fanout 4 [get_ports {layer2Input[8]}]
set_max_fanout 4 [get_ports {layer2Input[7]}]
set_max_fanout 4 [get_ports {layer2Input[6]}]
set_max_fanout 4 [get_ports {layer2Input[5]}]
set_max_fanout 4 [get_ports {layer2Input[4]}]
set_max_fanout 4 [get_ports {layer2Input[3]}]
set_max_fanout 4 [get_ports {layer2Input[2]}]
set_max_fanout 4 [get_ports {layer2Input[1]}]
set_max_fanout 4 [get_ports {layer2Input[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 1  -waveform {0 0.5}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.01 [get_clocks clk]
set_clock_transition -max -fall 0.01 [get_clocks clk]
set_clock_transition -min -rise 0.01 [get_clocks clk]
set_clock_transition -min -fall 0.01 [get_clocks clk]
set_input_delay -clock clk  0.05  [get_ports reset]
set_input_delay -clock clk  0.05  [get_ports inputsReady]
set_input_delay -clock clk  0.05  [get_ports outputsRecieved]
set_input_delay -clock clk  0.05  [get_ports weightWriteEnable]
set_input_delay -clock clk  0.05  [get_ports biasWriteEnable]
set_input_delay -clock clk  0.05  [get_ports {WriteAddressSelect[2]}]
set_input_delay -clock clk  0.05  [get_ports {WriteAddressSelect[1]}]
set_input_delay -clock clk  0.05  [get_ports {WriteAddressSelect[0]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[39]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[38]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[37]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[36]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[35]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[34]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[33]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[32]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[31]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[30]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[29]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[28]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[27]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[26]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[25]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[24]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[23]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[22]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[21]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[20]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[19]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[18]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[17]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[16]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[15]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[14]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[13]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[12]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[11]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[10]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[9]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[8]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[7]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[6]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[5]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[4]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[3]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[2]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[1]}]
set_input_delay -clock clk  0.05  [get_ports {writeIn[0]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[23]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[22]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[21]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[20]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[19]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[18]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[17]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[16]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[15]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[14]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[13]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[12]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[11]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[10]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[9]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[8]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[7]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[6]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[5]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[4]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[3]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[2]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[1]}]
set_input_delay -clock clk  0.05  [get_ports {layer2Input[0]}]
set_output_delay -clock clk  0.05  [get_ports inputsRecieved]
set_output_delay -clock clk  0.05  [get_ports outputsReady]
set_output_delay -clock clk  0.05  [get_ports {predictionOutput[3]}]
set_output_delay -clock clk  0.05  [get_ports {predictionOutput[2]}]
set_output_delay -clock clk  0.05  [get_ports {predictionOutput[1]}]
set_output_delay -clock clk  0.05  [get_ports {predictionOutput[0]}]
